version: 2.0
jobs:
 build:
   docker:
     - image: circleci/node:alpine
   steps:
     - checkout
     - run:
         name: npm installing
         command: |
           echo 'npm installing'
           npm install
           CI=true npm run build
 test:
   docker:
     - image: circleci/node:alpine
   steps:
     - checkout
     - run:
         name: testing
         command: |
           echo 'testing'
           npm install
           npm test
 hithere:
   docker:
     - image: circleci/node:alpine
   steps:
     - checkout
     - run:
         command:
           echo "hellooooo!"
workflows:
 version: 2
 build_test_and_lint:
   jobs:
     - build
     - hithere
     - test:
        requires:
         -hithere
