version: 2.0
jobs:
 build:
   docker:
     - image: circleci/node:11.10
   steps:
     - checkout
     - run:
         name: npm installing
         command: |
           echo 'npm installing'
           npm install
           CI=true npm run build
 test:
   docker:
     - image: circleci/node:alpine
   steps:
     - checkout
     - run:
         name: testing
         command: |
           echo 'testing'
           npm install
           npm test
workflows:
 version: 2
 build_test_and_lint:
   jobs:
     - build
     - test
